language: php

php:
    - 5.3
    - 5.4

sudo: false

dist: precise

env:
  - DB=MYSQL CORE_RELEASE=3.5

matrix:
  include:
    - php: 5.5
      env: DB=PGSQL CORE_RELEASE=3
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.2
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=3.6

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss
  - composer install

script:
    - vendor/bin/phpunit --coverage-clover coverage.clover sharedraftcontent/tests
    - wget https://scrutinizer-ci.com/ocular.phar
    - git remote rm origin
    - git remote add origin git@github.com:silverstripe-labs/silverstripe-sharedraftcontent.git
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

